use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{bail, Context, Result};
use serde::Serialize;

use super::gh::{gh_release_create, gh_release_exists};

/// Result returned by [`build_extension`] for use by `ext release`.
#[derive(Debug, Serialize)]
pub struct BuildExtResult {
    pub extension_js: bool,
    pub webview_js: bool,
    pub sinxt_path: Option<PathBuf>,
}

/// Resolve the `--ide-root` path.  Priority:
///   1. explicit `--ide-root` CLI arg
///   2. `SINDRI_IDE_ROOT` environment variable (CI compatibility)
///   3. `../sindri-ide` sibling of the repo root
pub(crate) fn resolve_ide_root(explicit: Option<&Path>, repo: &Path) -> Result<PathBuf> {
    if let Some(p) = explicit {
        if p.is_dir() {
            return Ok(p.to_path_buf());
        }
        bail!("--ide-root {} does not exist", p.display());
    }
    if let Ok(val) = std::env::var("SINDRI_IDE_ROOT") {
        let p = PathBuf::from(&val);
        if p.is_dir() {
            return Ok(p);
        }
        bail!("SINDRI_IDE_ROOT={val} does not exist");
    }
    // Guess: sibling of the extensions repo root.
    let sibling = repo
        .parent()
        .map(|p| p.join("sindri-ide"))
        .unwrap_or_else(|| PathBuf::from("../sindri-ide"));
    if sibling.is_dir() {
        return Ok(sibling);
    }
    bail!(
        "cannot locate sindri-ide: pass --ide-root <path> or set SINDRI_IDE_ROOT.\n\
         (tried sibling {sibling_display})",
        sibling_display = sibling.display()
    );
}

/// Ensure `packages/sindri-api/dist/helpers.js` is built and up to date.
/// Mirrors the staleness check in `sindri-ide/scripts/build-extension.ts`.
fn ensure_api_built(ide_root: &Path) -> Result<()> {
    let api_dir = ide_root.join("packages/sindri-api");
    let src = api_dir.join("helpers.ts");
    let out = api_dir.join("dist/helpers.js");

    let stale = !out.exists() || {
        let src_mtime = src
            .metadata()
            .with_context(|| format!("cannot stat {}", src.display()))?
            .modified()?;
        let out_mtime = out.metadata()?.modified()?;
        src_mtime > out_mtime
    };

    if stale {
        eprintln!("  building @sindri/api...");
        let status = Command::new("bun")
            .current_dir(&api_dir)
            .args(["run", "build"])
            .status()
            .context("failed to spawn `bun run build` for @sindri/api")?;
        if !status.success() {
            bail!("@sindri/api build failed");
        }
    }
    Ok(())
}

/// Generate a minimal esbuild TypeScript script for a single extension.
///
/// Rust controls all options (entry points, aliases, framework detection) and
/// writes them as JSON-escaped string literals into the script body.  The
/// script is run via `bun run <tmp>` from `ide_root` so it has access to
/// `esbuild` and `esbuild-sass-plugin` in `ide_root/node_modules`.
///
/// This is NOT delegation to a maintained `.ts` file — the script is generated
/// fresh each invocation and deleted afterwards (ADR-0033 §7 constraint).
fn generate_build_script(
    ext_dir: &Path,
    api_helpers: &Path,
    dev_sourcemaps: bool,
) -> String {
    let ext_dir_json = serde_json::to_string(&ext_dir.to_string_lossy().as_ref()).unwrap();
    let api_json = serde_json::to_string(&api_helpers.to_string_lossy().as_ref()).unwrap();
    // "inline" embeds the full source map + original source text as a data URL so
    // V8 Inspector / chrome://inspect can show .ts sources with no file fetching.
    // "linked" produces a separate .map file (used for release builds).
    let ext_sourcemap = if dev_sourcemaps { "inline" } else { "linked" };

    format!(
        r#"// Auto-generated by `sindri ext build` — do not edit; deleted after use.
import * as esbuild from "esbuild";
import {{ sassPlugin }} from "esbuild-sass-plugin";
import * as fs from "fs";
import * as path from "path";

const extDir = {ext_dir_json};
const apiHelpers = {api_json};

const fmtBytes = (n) => n >= 1e6 ? (n/1e6).toFixed(1)+' MB' : n >= 1e3 ? (n/1e3).toFixed(1)+' KB' : n+' B';
const logBuilt = (f) => console.log(`  built  ${{path.basename(f).padEnd(20)}}  ${{fmtBytes(fs.statSync(f).size)}}`);

// ── Extension bundle (IIFE, V8 isolate) ──────────────────────────────────────
const extEntry = path.join(extDir, "src/extension.ts");
if (fs.existsSync(extEntry)) {{
  await esbuild.build({{
    entryPoints: [extEntry],
    bundle: true,
    outfile: path.join(extDir, "dist/extension.js"),
    format: "iife",
    globalName: "sindri_ext",
    platform: "neutral",
    target: "es2020",
    sourcemap: "{ext_sourcemap}",
    sourcesContent: true,
    plugins: [sassPlugin()],
    alias: {{ "@sindri/api/helpers": apiHelpers }},
    logLevel: "warning",
  }});
  logBuilt(path.join(extDir, "dist/extension.js"));
}}

// ── Webview bundle (IIFE, browser) ───────────────────────────────────────────
const webviewCandidates = [
  "src/webview/index.tsx", "src/webview/index.ts", "src/webview.tsx", "src/webview.ts",
].map(f => path.join(extDir, f)).filter(f => fs.existsSync(f));

if (webviewCandidates.length > 0) {{
  const webviewEntry = webviewCandidates[0];
  const webviewOut = path.join(extDir, "dist/webview.js");

  let jsxOpts = {{}};
  let extraPlugins = [];
  const pkgPath = path.join(extDir, "package.json");
  // Also check bun.lock for workspace deps (bun lockfile v1 embeds dep list).
  const bunLock = path.join(extDir, "bun.lock");
  let deps = {{}};
  if (fs.existsSync(pkgPath)) {{
    const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
    deps = {{ ...pkg.dependencies, ...pkg.devDependencies }};
  }} else if (fs.existsSync(bunLock)) {{
    const lock = fs.readFileSync(bunLock, "utf8");
    // Heuristic: scan for known framework package names in the lockfile text.
    if (lock.includes('"svelte"')) deps["svelte"] = "^4";
    if (lock.includes('"react"')) deps["react"] = "^18";
    if (lock.includes('"solid-js"')) deps["solid-js"] = "^1";
    if (lock.includes('"preact"')) deps["preact"] = "^10";
  }}
  if (deps["svelte"]) {{
    const {{ default: sveltePlugin }} = await import("esbuild-svelte");
    const {{ default: preprocess }} = await import("svelte-preprocess");
    extraPlugins.push(sveltePlugin({{ preprocess: preprocess(), compilerOptions: {{ css: "injected" }} }}));
  }} else if (deps["solid-js"]) {{
    jsxOpts = {{ jsx: "automatic", jsxImportSource: "solid-js" }};
  }} else if (deps["react"]) {{
    jsxOpts = {{ jsx: "automatic", jsxImportSource: "react" }};
  }} else if (deps["preact"]) {{
    jsxOpts = {{ jsx: "automatic", jsxImportSource: "preact" }};
  }}

  await esbuild.build({{
    entryPoints: [webviewEntry],
    bundle: true,
    outfile: webviewOut,
    format: "iife",
    platform: "browser",
    target: "es2020",
    sourcemap: "linked",
    plugins: [sassPlugin(), ...extraPlugins],
    alias: {{ "@sindri/api/helpers": apiHelpers }},
    logLevel: "warning",
    ...jsxOpts,
  }});
  logBuilt(webviewOut);
  const webviewCss = webviewOut.replace(/\.js$/, ".css");
  if (fs.existsSync(webviewCss)) logBuilt(webviewCss);
}}
"#,
        ext_sourcemap = ext_sourcemap,
        ext_dir_json = ext_dir_json,
        api_json = api_json,
    )
}

/// Core build logic shared by `ext build` and `ext release`.
///
/// 1. Validates the manifest.
/// 2. Ensures `@sindri/api` is built.
/// 3. Generates + runs an esbuild script for the JS bundle step.
/// 4. If `bundle`, collects files and packs a `.sinxt`.
///
/// Returns details about what was produced.
pub(crate) fn build_extension(ext_dir: &Path, ide_root: &Path, bundle: bool, dev_sourcemaps: bool) -> Result<BuildExtResult> {
    // --- Validate manifest ---------------------------------------------------
    let manifest_path = ext_dir.join("manifest.json");
    let raw = std::fs::read_to_string(&manifest_path)
        .with_context(|| format!("no manifest.json at {}", ext_dir.display()))?;
    let value: serde_json::Value = serde_json::from_str(&raw)
        .with_context(|| format!("invalid JSON in {}", manifest_path.display()))?;
    let issues = sindri_core::validate(&value);
    if !issues.is_empty() {
        eprintln!("✘ manifest validation failed ({}):", ext_dir.display());
        for i in &issues {
            eprintln!("    {}: {}", i.field, i.message);
        }
        bail!("manifest validation failed");
    }
    let manifest: sindri_core::Manifest = serde_json::from_value(value)?;

    // --- @sindri/api freshness check ----------------------------------------
    ensure_api_built(ide_root)?;
    let api_helpers = ide_root.join("packages/sindri-api/dist/helpers.js");

    // --- JS bundle step (shell bun esbuild via generated temp script) --------
    let has_ext_entry = ext_dir.join("src/extension.ts").is_file();
    let webview_candidates = [
        "src/webview/index.tsx",
        "src/webview/index.ts",
        "src/webview.tsx",
        "src/webview.ts",
    ]
    .iter()
    .any(|f| ext_dir.join(f).is_file());
    let needs_js = has_ext_entry || webview_candidates;

    if needs_js {
        let script = generate_build_script(ext_dir, &api_helpers, dev_sourcemaps);
        // Write the temp script into ide_root so bun resolves node_modules
        // relative to the script's directory (bun ignores CWD for resolution).
        let tmp = ide_root.join(format!(".sindri_build_{}.ts", std::process::id()));
        std::fs::write(&tmp, &script)
            .with_context(|| format!("cannot write temp build script {}", tmp.display()))?;
        let result = Command::new("bun")
            .current_dir(ide_root)
            .args(["run", tmp.to_str().unwrap()])
            .status();
        let _ = std::fs::remove_file(&tmp);
        let status = result.context("failed to spawn bun for JS bundle step")?;
        if !status.success() {
            bail!("JS bundle step failed for {}", ext_dir.display());
        }
    }

    // --- .sinxt packaging (Rust-native) -------------------------------------
    let sinxt_path = if bundle {
        // Post-build path validation
        let missing = sindri_core::validate_paths(ext_dir, &manifest);
        if !missing.is_empty() {
            eprintln!("✘ manifest references missing files:");
            for m in &missing {
                eprintln!("    {m}");
            }
            bail!("post-build path validation failed");
        }

        let files = sindri_core::collect_package_files(ext_dir, &manifest)?;
        let bytes = sindri_core::pack_sinxt(ext_dir, &files)?;

        let dist = ext_dir.join("dist");
        std::fs::create_dir_all(&dist)?;
        // Remove any previous .sinxt for this extension.
        for entry in std::fs::read_dir(&dist)? {
            let entry = entry?;
            if entry
                .path()
                .extension()
                .is_some_and(|e| e == "sinxt")
            {
                std::fs::remove_file(entry.path())?;
            }
        }

        let out_name = format!("{}-{}.sinxt", manifest.id, manifest.version);
        let out_path = dist.join(&out_name);
        std::fs::write(&out_path, &bytes)?;

        let kb = bytes.len() as f64 / 1_000.0;
        println!(
            "  ✓ dist/{out_name}  ({} files · {kb:.1} KB)",
            files.len()
        );
        Some(out_path)
    } else {
        None
    };

    Ok(BuildExtResult {
        extension_js: has_ext_entry,
        webview_js: webview_candidates,
        sinxt_path,
    })
}

// ── `ext build` entrypoint ────────────────────────────────────────────────────

pub fn build(
    path: &str,
    bundle: bool,
    dev_sourcemaps: bool,
    ide_root_arg: Option<&std::path::Path>,
    json: bool,
) -> Result<i32> {
    let ext_dir = PathBuf::from(path);
    if !ext_dir.join("manifest.json").is_file() {
        bail!("no manifest.json at {path}");
    }

    // For ide_root resolution, use the ext_dir as the "repo" hint.
    let ide_root = resolve_ide_root(ide_root_arg, &ext_dir)?;
    let result = build_extension(&ext_dir, &ide_root, bundle, dev_sourcemaps)?;

    if json {
        #[derive(Serialize)]
        struct Out {
            path: String,
            extension_js: bool,
            webview_js: bool,
            sinxt_path: Option<String>,
        }
        println!(
            "{}",
            serde_json::to_string_pretty(&Out {
                path: path.to_string(),
                extension_js: result.extension_js,
                webview_js: result.webview_js,
                sinxt_path: result
                    .sinxt_path
                    .map(|p| p.to_string_lossy().into_owned()),
            })?
        );
    } else if !result.extension_js && !result.webview_js && result.sinxt_path.is_none() {
        println!("✓ {path} — data-only extension (no JS to bundle)");
        if bundle {
            println!("  .sinxt written");
        }
    }

    Ok(0)
}

// ── `ext release` entrypoint ─────────────────────────────────────────────────

/// A per-extension release outcome for `--json` output.
#[derive(Serialize)]
struct ReleaseOutcome {
    id: String,
    version: String,
    tag: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    status: Option<&'static str>,
    #[serde(skip_serializing_if = "Option::is_none")]
    reason: Option<&'static str>,
}

pub fn release(repo: Option<PathBuf>, ide_root_arg: Option<PathBuf>, json: bool) -> Result<i32> {
    let root = super::version::repo_root(repo)?;
    let ide_root = resolve_ide_root(ide_root_arg.as_deref(), &root)?;

    // Scan top-level dirs — mirrors create-releases.ts behaviour.
    let mut candidates = Vec::new();
    for entry in std::fs::read_dir(&root)? {
        let entry = entry?;
        let name = entry.file_name();
        let name_str = name.to_string_lossy();
        if !entry.path().is_dir() || name_str.starts_with('.') || name_str == "node_modules" {
            continue;
        }
        let manifest_path = entry.path().join("manifest.json");
        if manifest_path.is_file() {
            candidates.push(entry.path());
        }
    }
    candidates.sort();

    let mut outcomes: Vec<ReleaseOutcome> = Vec::new();
    let mut released = 0u32;
    let mut failed = 0u32;

    for dir in &candidates {
        let raw = std::fs::read_to_string(dir.join("manifest.json"))?;
        let manifest: sindri_core::Manifest = serde_json::from_str(&raw)?;

        if !manifest.is_buildable() {
            // buildable: false — skip entirely (no release, no error).
            continue;
        }

        let tag = manifest.release_tag();

        if gh_release_exists(&root, &tag) {
            if !json {
                println!("✓ {}@{} already released", manifest.id, manifest.version);
            }
            outcomes.push(ReleaseOutcome {
                id: manifest.id.clone(),
                version: manifest.version.clone(),
                tag: tag.clone(),
                status: Some("skipped"),
                reason: Some("already_tagged"),
            });
            continue;
        }

        if !json {
            println!("\n── Releasing {}@{} ──", manifest.id, manifest.version);
        }

        let build_result = build_extension(dir, &ide_root, true, false);
        let sinxt_path = match build_result {
            Err(e) => {
                eprintln!("✘ Build failed: {} — {e:#}", manifest.id);
                failed += 1;
                outcomes.push(ReleaseOutcome {
                    id: manifest.id.clone(),
                    version: manifest.version.clone(),
                    tag: tag.clone(),
                    status: Some("failed"),
                    reason: Some("build_failed"),
                });
                continue;
            }
            Ok(r) => match r.sinxt_path {
                Some(p) => p,
                None => {
                    eprintln!("✘ No .sinxt produced for {}", manifest.id);
                    failed += 1;
                    outcomes.push(ReleaseOutcome {
                        id: manifest.id.clone(),
                        version: manifest.version.clone(),
                        tag: tag.clone(),
                        status: Some("failed"),
                        reason: Some("no_sinxt"),
                    });
                    continue;
                }
            },
        };

        let is_prerelease = manifest.version.contains('-');
        if let Err(e) = gh_release_create(
            &root,
            &tag,
            &format!("{} v{}", manifest.name, manifest.version),
            &format!("Release of `{}` v{}.", manifest.id, manifest.version),
            &sinxt_path,
            is_prerelease,
        ) {
            eprintln!("✘ Release failed: {} — {e:#}", manifest.id);
            failed += 1;
            outcomes.push(ReleaseOutcome {
                id: manifest.id.clone(),
                version: manifest.version.clone(),
                tag: tag.clone(),
                status: Some("failed"),
                reason: Some("gh_release_failed"),
            });
            continue;
        }

        if !json {
            println!("✓ Released {tag}");
        }
        released += 1;
        outcomes.push(ReleaseOutcome {
            id: manifest.id.clone(),
            version: manifest.version.clone(),
            tag: tag.clone(),
            status: Some("released"),
            reason: None,
        });
    }

    if json {
        println!("{}", serde_json::to_string_pretty(&outcomes)?);
    } else {
        println!("\n{released} released, {failed} failed.");
    }

    Ok(if failed > 0 { 1 } else { 0 })
}

// ── `ext build-index` entrypoint ─────────────────────────────────────────────

/// Regenerates `index.json` from individual `manifest.json` files (ADR-0038 §2).
/// Emits a flat `entries: [{id, path, type}]` array — every extension, pack,
/// collection, and template in the registry, each with its authoritative path.
/// Preserves `name`/`description`/`homepage` from the existing `index.json`.
pub fn build_index(repo: Option<PathBuf>, json: bool) -> Result<i32> {
    let root = match repo {
        Some(p) => p,
        None => std::env::current_dir().context("cannot read current directory")?,
    };

    const SKIP: &[&str] = &["node_modules", "dist", "scripts", ".git"];

    // ── Discover all manifest.json files ─────────────────────────────────────
    struct Entry {
        rel_dir: String,
        manifest: sindri_core::Manifest,
    }

    fn find_manifests(dir: &Path, root: &Path, skip: &[&str], out: &mut Vec<Entry>) -> Result<()> {
        let mut entries: Vec<_> = std::fs::read_dir(dir)?.filter_map(|e| e.ok()).collect();
        entries.sort_by_key(|e| e.file_name());
        for entry in entries {
            let name = entry.file_name();
            let name_str = name.to_string_lossy();
            if skip.contains(&name_str.as_ref()) { continue; }
            let path = entry.path();
            if path.is_dir() {
                find_manifests(&path, root, skip, out)?;
            } else if name_str == "manifest.json" {
                let raw = std::fs::read_to_string(&path)
                    .with_context(|| format!("cannot read {}", path.display()))?;
                let manifest: sindri_core::Manifest = serde_json::from_str(&raw)
                    .with_context(|| format!("invalid JSON in {}", path.display()))?;
                let rel_dir = path
                    .parent()
                    .map(|p| p.strip_prefix(root).unwrap_or(p).to_string_lossy().replace('\\', "/"))
                    .unwrap_or_default();
                out.push(Entry { rel_dir, manifest });
            }
        }
        Ok(())
    }

    let mut all: Vec<Entry> = Vec::new();
    find_manifests(&root, &root, SKIP, &mut all)?;

    // ── Determine type for each manifest ─────────────────────────────────────
    // Use the manifest's own `type` field when present; fall back to category inference.
    fn infer_type(m: &sindri_core::Manifest) -> String {
        if let Some(t) = &m.manifest_type {
            return t.clone();
        }
        let is_pack = m.categories.iter().any(|c| c == "Extension Pack");
        let is_base = m.categories.iter().any(|c| c == "Icon Theme Base");
        if is_base { return "template".to_string(); }
        if is_pack {
            if m.pack_kind.as_deref() == Some("theme") { "collection".to_string() }
            else { "pack".to_string() }
        } else {
            "extension".to_string()
        }
    }

    // ── Build the flat entries list ───────────────────────────────────────────
    #[derive(serde::Serialize)]
    struct IndexEntry {
        id: String,
        path: String,
        #[serde(rename = "type")]
        kind: String,
    }

    let mut entries: Vec<IndexEntry> = all
        .iter()
        .filter(|e| e.manifest.available != Some(false) && e.manifest.buildable != Some(false))
        .map(|e| IndexEntry {
            id: e.manifest.id.clone(),
            path: e.rel_dir.clone(),
            kind: infer_type(&e.manifest),
        })
        .collect();

    // Sort: top-level entries first (collection → pack → extension), then by id.
    // Template entries sort alongside extensions.
    fn type_rank(t: &str) -> u8 {
        match t {
            "collection" => 0,
            "pack"       => 1,
            _            => 2,
        }
    }
    entries.sort_unstable_by(|a, b| {
        type_rank(&a.kind).cmp(&type_rank(&b.kind)).then(a.id.cmp(&b.id))
    });

    // ── Preserve existing registry metadata ───────────────────────────────────
    let index_path = root.join("index.json");
    let (meta_name, meta_description, meta_homepage) = if index_path.is_file() {
        let raw = std::fs::read_to_string(&index_path).unwrap_or_default();
        if let Ok(v) = serde_json::from_str::<serde_json::Value>(&raw) {
            (
                v["name"].as_str().unwrap_or("").to_string(),
                v["description"].as_str().unwrap_or("").to_string(),
                v["homepage"].as_str().unwrap_or("").to_string(),
            )
        } else {
            (String::new(), String::new(), String::new())
        }
    } else {
        (String::new(), String::new(), String::new())
    };

    // ── Write index.json ──────────────────────────────────────────────────────
    #[derive(serde::Serialize)]
    struct Index {
        name: String,
        description: String,
        homepage: String,
        entries: Vec<IndexEntry>,
    }
    let index = Index {
        name: meta_name,
        description: meta_description,
        homepage: meta_homepage,
        entries,
    };
    let out = serde_json::to_string_pretty(&index)? + "\n";
    std::fs::write(&index_path, &out)?;

    if json {
        println!("{}", serde_json::to_string_pretty(&index)?);
    } else {
        let n_collections = index.entries.iter().filter(|e| e.kind == "collection").count();
        let n_packs       = index.entries.iter().filter(|e| e.kind == "pack").count();
        let n_extensions  = index.entries.iter().filter(|e| e.kind == "extension").count();
        let n_templates   = index.entries.iter().filter(|e| e.kind == "template").count();
        println!(
            "✓ index.json — {} entries ({} collections, {} packs, {} extensions, {} templates)",
            index.entries.len(), n_collections, n_packs, n_extensions, n_templates
        );
        for e in &index.entries { println!("  {} {}  ({})", e.kind, e.id, e.path); }
    }

    Ok(0)
}
